kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  name: ytgh
  namespace: hce
  creationTimestamp: null
  labels:
    infra_id: 39519a6d-f864-492f-b92b-e8c99e520581
    revision_id: 8d3cbf6d-d35e-49f3-bace-00209bd14344
    workflow_id: 2e4f034f-5904-4403-adfc-09b3cafb6e34
    workflows.argoproj.io/controller-instanceid: 39519a6d-f864-492f-b92b-e8c99e520581
spec:
  templates:
    - name: pod-del
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: pod-delete-60u
            template: pod-delete-60u
            arguments: {}
        - - name: cleanup-chaos-resources
            template: cleanup-chaos-resources
            arguments: {}
    - name: cleanup-chaos-resources
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: docker.io/harness/chaos-go-runner:1.44.0
        command:
          - sh
          - -c
        args:
          - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n
            {{workflow.parameters.adminModeNamespace}}
        resources: {}
    - name: pod-delete-60u
      inputs:
        artifacts:
          - name: pod-delete-60u
            path: /tmp/chaosengine-pod-delete-60u.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                kind: ChaosEngine

                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  labels:
                    name: pod-delete
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: experiment-job
                    app.kubernetes.io/version: ci
                    workflow_run_id: "{{ workflow.uid }}"
                    workflow_name: pod-del
                  annotations:
                    probeRef: '[{"probeID":"default-harness-k8s-system-cmd-probe","mode":"SOT"}]'
                  generateName: pod-delete-60u
                spec:
                  appinfo:
                    appns: hce
                    applabel: app=chaos-exporter
                    appkind: deployment
                  engineState: active
                  terminationGracePeriodSeconds: 30
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-delete
                      image: docker.io/harness/chaos-go-runner:1.44.1
                      imagePullPolicy: Always
                      args:
                        - -c
                        - ./experiments -name pod-delete
                      command:
                        - /bin/bash
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "30"
                            - name: RAMP_TIME
                              value: ""
                            - name: FORCE
                              value: "false"
                            - name: CHAOS_INTERVAL
                              value: "10"
                            - name: PODS_AFFECTED_PERC
                              value: ""
                            - name: TARGET_CONTAINER
                              value: ""
                            - name: TARGET_PODS
                              value: ""
                            - name: DEFAULT_HEALTH_CHECK
                              value: "false"
                            - name: NODE_LABEL
                              value: ""
                            - name: SEQUENCE
                              value: parallel
                          experimentImagePullSecrets:
                            - name: test
                          securityContext:
                            podSecurityContext:
                              runAsUser: 2000
                              runAsGroup: 0
                  jobCleanUpPolicy: delete
                  components:
                    runner:
                      imagePullSecrets:
                        - name: test
      outputs: {}
      metadata:
        labels:
          weight: "10"
      container:
        name: ""
        image: docker.io/harness/chaos-go-runner:1.44.0
        command:
          - ./chaos-checker
        args:
          - -file=/tmp/chaosengine-pod-delete-60u.yaml
          - -saveName=/tmp/engine-name
        resources: {}
  entrypoint: pod-del
  arguments:
    parameters:
      - name: adminModeNamespace
        value: hce
  serviceAccountName: argo-chaos
  imagePullSecrets:
    - name: test
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsUser: 1000
    runAsGroup: 0
    runAsNonRoot: true
status:
  startedAt: null
  finishedAt: null
