kind: KubernetesChaosExperiment
apiVersion: litmuschaos.io/v1alpha1
metadata:
  name: tefdsd
  namespace: harness-delegate-ng
  creationTimestamp: null
spec:
  tasks:
    - name: pod-delete-okt
      definition:
        targets:
          appinfo:
            appns: ""
            applabel: ""
            appkind: ""
          selectors:
            workloads:
              - kind: deployment
                namespace: ""
                names: ""
                labels: ""
            pods: []
        chaos:
          cleanupPolicy: ""
          experiment: pod-delete
          image: docker.io/harness/chaos-ddcr-faults:1.45.0
          imagePullPolicy: Always
          labels: null
          annotations: null
          command: null
          args: null
          defaultHealthCheck: false
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"
            - name: CHAOS_INTERVAL
              value: "10"
            - name: FORCE
              value: "false"
            - name: RAMP_TIME
            - name: POD_AFFECTED_PERCENTAGE
            - name: TARGET_PODS
            - name: NODE_LABEL
            - name: SEQUENCE
              value: parallel
          probes: null
          components:
            resources: {}
      probeRef:
        - probeID: cart-service-availability-check
          mode: SOT
  experimentId: b7b77396-47ff-4af2-85c0-c0875a5ff201
  experimentRunId: ""
  steps:
    - - name: pod-delete-okt
        status: ""
  cleanupPolicy: delete
  serviceAccountName: litmus
